/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package widok;

import dane.JednostkaOrganizacyjna;
import dane.Pacjent;
import dane.Pobyt;
import dane.zrodlaDanych.JednostkaOrganizacyjnaZrodlo;
import dane.zrodlaDanych.PobytZrodlo;
import java.awt.Color;
import java.awt.Dialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author brybarczyk
 */
public class OknoEdycji extends javax.swing.JDialog {

    /**
     * Creates new form OknoEdycji
     */
    private PobytZrodlo pbZrodlo;
    private JednostkaOrganizacyjnaZrodlo joZrodlo;
    private Pobyt pb1;
    private JednostkaOrganizacyjna jo1;

    public OknoEdycji() {
        initComponents();
    }

    public OknoEdycji(Pobyt pb) throws SQLException {
        initComponents();
        jLabel5.setVisible(false);
        pbZrodlo = new PobytZrodlo();
        pb1 = pbZrodlo.pobierzDanePobytuBD(pb.getId());
        Pacjent pc1 = pb1.getPacjent();
        tfEdycjaImie.setText(pc1.getImie());
        tfEdycjaNazwisko.setText(pc1.getNazwisko());
        joZrodlo = new JednostkaOrganizacyjnaZrodlo();
        ArrayList<JednostkaOrganizacyjna> listaOddzial;
        try {
            listaOddzial = joZrodlo.pobierzJednostki();
            wczytajListeOddzialow(listaOddzial);
        } catch (SQLException ex) {
            Logger.getLogger(OknoGlowne.class.getName()).log(Level.SEVERE, null, ex);
        }
        jo1 = pb1.getJo();
        cbJednostkaOrganizacyjnaOE.setSelectedItem(jo1);
        this.setTitle("Okno edycji");
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);    // ustawienie okna, jako modalne
        this.setAlwaysOnTop(true);
        this.setVisible(true);

    }

    private void wczytajListeOddzialow(ArrayList<JednostkaOrganizacyjna> listaOddzialow) {
        cbJednostkaOrganizacyjnaOE.addItem(new JednostkaOrganizacyjna(0, ""));
        for (JednostkaOrganizacyjna jo : listaOddzialow) {
            cbJednostkaOrganizacyjnaOE.addItem(jo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEdycjaImie = new javax.swing.JTextField();
        tfEdycjaNazwisko = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bZapisz = new javax.swing.JButton();
        cbJednostkaOrganizacyjnaOE = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Imię: ");

        jLabel2.setText("Nazwisko: ");

        jLabel3.setText("Oddział:");

        tfEdycjaImie.setText("jTextField1");

        tfEdycjaNazwisko.setText("jTextField2");

        jLabel4.setText("Edycja pacjenta w pobycie");

        bZapisz.setText("Zapisz");
        bZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZapiszActionPerformed(evt);
            }
        });

        jLabel5.setText("Aktualizacja zaakceptowana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEdycjaNazwisko)
                            .addComponent(cbJednostkaOrganizacyjnaOE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfEdycjaImie)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bZapisz)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfEdycjaImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEdycjaNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbJednostkaOrganizacyjnaOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bZapisz)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZapiszActionPerformed

        try {
            JednostkaOrganizacyjna jo2 = (JednostkaOrganizacyjna) cbJednostkaOrganizacyjnaOE.getSelectedItem();
            if (jo2.getId() != 0) {
                pbZrodlo.aktualizujDanePobytuBD(pb1.getId(), tfEdycjaImie.getText(), tfEdycjaNazwisko.getText(), jo2.getId());
                System.out.println("jo.getId= " + jo2.getId() + "\njo.getNazwa= " + jo2.getNazwa());

            }
            jLabel5.setVisible(true);
            jLabel5.setForeground(Color.green);
            TimeUnit.SECONDS.sleep(3);
            jLabel5.setVisible(false);
        } catch (InterruptedException | SQLException ex) {
            Logger.getLogger(OknoEdycji.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("\ngetSelectedIndex(): \t" + cbJednostkaOrganizacyjnaOE.getSelectedIndex());
        System.out.println("getSelectedItem(): \t" + cbJednostkaOrganizacyjnaOE.getSelectedItem());
        System.out.println("getSelectedObjects(): \t" + cbJednostkaOrganizacyjnaOE.getSelectedObjects());
    }//GEN-LAST:event_bZapiszActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bZapisz;
    private javax.swing.JComboBox<JednostkaOrganizacyjna> cbJednostkaOrganizacyjnaOE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfEdycjaImie;
    private javax.swing.JTextField tfEdycjaNazwisko;
    // End of variables declaration//GEN-END:variables
}
