/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package widok;

import dane.Badanie;
import dane.Ekg;
import dane.Pobyt;
import dane.Usg;
import dane.zrodlaDanych.BadanieZrodlo;
import dane.zrodlaDanych.EkgZrodlo;
import dane.zrodlaDanych.PobytZrodlo;
import dane.zrodlaDanych.UsgZrodlo;
import java.awt.Dialog;
import java.math.BigDecimal;
import java.util.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author brybarczyk
 */
public class OknoSzczegolowe extends javax.swing.JDialog {      //zmiana dziedziczenia javax.swing.JFrame na javax.swing.JDialog

    /**
     * Creates new form OknoSzczegolowe
     */
    private final PobytZrodlo pbZrodlo;
    private final BadanieZrodlo bZrodlo;
    private final Pobyt pbOSZ;
    private EkgZrodlo eZrodlo;
    private UsgZrodlo uZrodlo;
    private Ekg e;
    private Usg u;

    public OknoSzczegolowe(Pobyt pb) throws SQLException {
        initComponents();
        pbZrodlo = new PobytZrodlo();
        bZrodlo = new BadanieZrodlo();
        eZrodlo = new EkgZrodlo();
        uZrodlo = new UsgZrodlo();
        e = new Ekg();
        u = new Usg();
        
        pbOSZ = pbZrodlo.pobierzDanePobytuBD(pb.getId());
        taPacjent.setText(pbOSZ.getPacjent().toString());    // update pobyt_pobierz_dane
        taPobyt.setText(pbOSZ.toString());
        taLekarz.setText(pbOSZ.getLekarz() + "\n"
                + "\nData przyjecia=\t" + pbOSZ.getDataOd()
                + "\nData wypisu=\t" + pbOSZ.getDataDo());

        wczytajListeBadan(1, cbEkgLista, bUsunEkg);
        wczytajListeBadan(2, cbUsgLista, bUsunUsg);
        wczytajListeNazwUsg();
        cbUsgListaNazw.setSelectedItem(u);
        this.setTitle("Okno Szczegółowe");
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);    // ustawienie okna, jako modalne
        this.setVisible(true);
    }

    public Pobyt getPbOSZ() {
        return pbOSZ;
    }

    private void wczytajListeBadan(int rodzajBadania, JComboBox<Badanie> cbBadanieLista, JButton bUsunBadanie) throws SQLException {
        ArrayList<Badanie> listaBadan;
        listaBadan = bZrodlo.pobierzBadanieListaBD(pbOSZ.getId(), rodzajBadania);
        if (!listaBadan.isEmpty()) {
            for (Badanie b : listaBadan) {
                cbBadanieLista.addItem(b);
            }
        } else {
            bUsunBadanie.setEnabled(false);
        }
    }

    private void wczytajListeNazwUsg() throws SQLException {
        ArrayList<Usg> listaNazw;
        listaNazw = uZrodlo.pobierzNazwyWynikowUsg();
        for (Usg un : listaNazw) {
            cbUsgListaNazw.addItem(un);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Formularze = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPobyt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taPacjent = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLekarz = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        tpBadania = new javax.swing.JTabbedPane();
        pEkg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfEkgPobyt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfEkgLekarz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEkgDataBad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfEkgOpis = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tfEkgRytm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfEkgWar1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfEkgWar2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lListaBadanEkg = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cbEkgLista = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tfEkgId = new javax.swing.JTextField();
        bUsunEkg = new javax.swing.JButton();
        bZapiszEkg = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        pUsg = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfUsgPobyt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfUsgLekarz = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfUsgDataBad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tfUsgOpis = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lListaBadanUsg = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cbUsgLista = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        tfUsgId = new javax.swing.JTextField();
        bUsunUsg = new javax.swing.JButton();
        bZapiszUsg = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        cbUsgListaNazw = new javax.swing.JComboBox<>();
        pDodajBadanie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(null);

        taPobyt.setEditable(false);
        taPobyt.setColumns(20);
        taPobyt.setRows(5);
        jScrollPane1.setViewportView(taPobyt);

        Formularze.addTab("Pobyt", jScrollPane1);

        taPacjent.setColumns(20);
        taPacjent.setRows(5);
        jScrollPane3.setViewportView(taPacjent);

        Formularze.addTab("Pacjent", jScrollPane3);

        taLekarz.setColumns(20);
        taLekarz.setRows(5);
        jScrollPane2.setViewportView(taLekarz);

        Formularze.addTab("Lekarz", jScrollPane2);

        tpBadania.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpBadaniaStateChanged(evt);
            }
        });

        jLabel4.setText("Pobyt pacjenta: ");

        tfEkgPobyt.setEditable(false);

        jLabel5.setText("Lekarz opisujący:");

        jLabel6.setText("Data badania:");

        jLabel7.setText("Wynik opisowy:");

        tfEkgOpis.setColumns(20);
        tfEkgOpis.setRows(5);
        jScrollPane5.setViewportView(tfEkgOpis);

        jLabel8.setText("Parametry EKG:");

        jLabel9.setText("Rytm:");

        jLabel10.setText("Wartość 1: ");

        jLabel11.setText("Wartość 2:");

        lListaBadanEkg.setText("Lista badań:");

        cbEkgLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEkgListaItemStateChanged(evt);
            }
        });

        jLabel13.setText("Id badania:");

        tfEkgId.setEditable(false);

        bUsunEkg.setText("Usuń");
        bUsunEkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsunEkgActionPerformed(evt);
            }
        });

        bZapiszEkg.setText("Zapisz");
        bZapiszEkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZapiszEkgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEkgLayout = new javax.swing.GroupLayout(pEkg);
        pEkg.setLayout(pEkgLayout);
        pEkgLayout.setHorizontalGroup(
            pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEkgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEkgLayout.createSequentialGroup()
                        .addComponent(lListaBadanEkg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEkgLayout.createSequentialGroup()
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pEkgLayout.createSequentialGroup()
                                .addComponent(cbEkgLista, 0, 181, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pEkgLayout.createSequentialGroup()
                                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEkgLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                                    .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfEkgWar1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfEkgRytm, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfEkgDataBad, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfEkgLekarz, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfEkgPobyt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfEkgWar2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfEkgId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pEkgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bUsunEkg)
                                .addGap(18, 18, 18)
                                .addComponent(bZapiszEkg)))
                        .addGap(18, 18, 18))))
        );
        pEkgLayout.setVerticalGroup(
            pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEkgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lListaBadanEkg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addComponent(cbEkgLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pEkgLayout.createSequentialGroup()
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEkgId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfEkgPobyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfEkgLekarz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfEkgDataBad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfEkgRytm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEkgWar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEkgWar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(4, 4, 4)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pEkgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bUsunEkg)
                    .addComponent(bZapiszEkg))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        tpBadania.addTab("EKG", pEkg);

        jLabel14.setText("Pobyt pacjenta: ");

        tfUsgPobyt.setEditable(false);

        jLabel15.setText("Lekarz opisujący:");

        jLabel16.setText("Data badania:");

        jLabel17.setText("Wynik opisowy:");

        tfUsgOpis.setColumns(20);
        tfUsgOpis.setRows(5);
        jScrollPane6.setViewportView(tfUsgOpis);

        jLabel19.setText("Rodzaj badania  USG: ");

        lListaBadanUsg.setText("Lista badań:");

        cbUsgLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUsgListaItemStateChanged(evt);
            }
        });

        jLabel23.setText("Id badania:");

        tfUsgId.setEditable(false);

        bUsunUsg.setText("Usuń");
        bUsunUsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsunUsgActionPerformed(evt);
            }
        });

        bZapiszUsg.setText("Zapisz");
        bZapiszUsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZapiszUsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUsgLayout = new javax.swing.GroupLayout(pUsg);
        pUsg.setLayout(pUsgLayout);
        pUsgLayout.setHorizontalGroup(
            pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUsgLayout.createSequentialGroup()
                        .addComponent(lListaBadanUsg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsgLayout.createSequentialGroup()
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pUsgLayout.createSequentialGroup()
                                .addComponent(cbUsgLista, 0, 181, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pUsgLayout.createSequentialGroup()
                                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbUsgListaNazw, 0, 247, Short.MAX_VALUE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(tfUsgDataBad, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfUsgLekarz, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfUsgPobyt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfUsgId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pUsgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bUsunUsg)
                                .addGap(18, 18, 18)
                                .addComponent(bZapiszUsg)))
                        .addGap(18, 18, 18))))
        );
        pUsgLayout.setVerticalGroup(
            pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lListaBadanUsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addComponent(jSeparator5))
                    .addComponent(cbUsgLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pUsgLayout.createSequentialGroup()
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUsgId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfUsgPobyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfUsgLekarz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfUsgDataBad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cbUsgListaNazw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pUsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bUsunUsg)
                    .addComponent(bZapiszUsg))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        tpBadania.addTab("USG", pUsg);
        pUsg.getAccessibleContext().setAccessibleName("USG");

        javax.swing.GroupLayout pDodajBadanieLayout = new javax.swing.GroupLayout(pDodajBadanie);
        pDodajBadanie.setLayout(pDodajBadanieLayout);
        pDodajBadanieLayout.setHorizontalGroup(
            pDodajBadanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        pDodajBadanieLayout.setVerticalGroup(
            pDodajBadanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        tpBadania.addTab("+", pDodajBadanie);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpBadania, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tpBadania, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpBadania.getAccessibleContext().setAccessibleName("USG");

        Formularze.addTab("Badania", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Formularze)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Formularze)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpBadaniaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpBadaniaStateChanged
        if (pDodajBadanie.isShowing()) {
            Object[] rodzajBadania = {"EKG", "USG"};
            String s = (String) JOptionPane.showInputDialog(
                    this,
                    "Nowe badanie...",
                    "Dodawanie nowego badania",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    rodzajBadania,
                    "EKG");
            switch (s) {
                case "EKG": {
                    tpBadania.setSelectedComponent(pEkg);
                    lListaBadanEkg.setText("Dodawanie nowego badania EKG: ");
                    cbEkgLista.setVisible(false);
                    tfEkgId.setText("");
                    tfEkgPobyt.setText(String.valueOf(e.getPb().getId()));
                    tfEkgLekarz.setText("");
                    tfEkgDataBad.setText("");
                    tfEkgOpis.setText("");
                    tfEkgRytm.setText("");
                    tfEkgWar1.setText("");
                    tfEkgWar2.setText("");
                    break;
                }
                case "USG": {
                    tpBadania.setSelectedComponent(pUsg);
                    lListaBadanUsg.setText("Dodawanie nowego badania USG: ");
                    cbUsgLista.setVisible(false);
                    tfUsgId.setText("");
                    tfUsgPobyt.setText(String.valueOf(u.getPb().getId()));
                    tfUsgLekarz.setText("");
                    tfUsgDataBad.setText("");
                    tfUsgOpis.setText("");
                    cbUsgListaNazw.setSelectedItem(null);
                    break;
                }
            }
        }
    }//GEN-LAST:event_tpBadaniaStateChanged

    private void bZapiszUsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZapiszUsgActionPerformed
        uZrodlo = new UsgZrodlo();
        int weBId = tfUsgId.getText() == null || tfUsgId.getText().isEmpty() ? 0 : Integer.parseInt(tfUsgId.getText());
        int wePbId = Integer.parseInt(tfUsgPobyt.getText());
        int weBLk = Integer.parseInt(tfUsgLekarz.getText());
        Date weBDataBad = null;
        try {
            weBDataBad = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(tfUsgDataBad.getText());
        } catch (ParseException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
        String weBOpis = tfUsgOpis.getText();
        int weUNId = cbUsgListaNazw.getSelectedItem() == null ? 0 : ((Usg) cbUsgListaNazw.getSelectedItem()).getNazwaId();

        try {
            if (weBId == 0) {
                weBId = uZrodlo.dodajBadanieUsg(wePbId, weBLk, weBDataBad, weBOpis, weUNId);
                tfUsgId.setText(String.valueOf(weBId));
                JOptionPane.showMessageDialog(this, "Dodano badanie " + weBId);
            } else {
                uZrodlo.aktualizujBadanieUsg(weBId, weBLk, weBDataBad, weBOpis, weUNId);
                JOptionPane.showMessageDialog(this, "Zaktualizowano badanie " + weBId);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
        lListaBadanUsg.setText("Lista badań: ");
        cbUsgLista.setVisible(true);
    }//GEN-LAST:event_bZapiszUsgActionPerformed

    private void bUsunUsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsunUsgActionPerformed
        usunBadanie(cbUsgLista);
    }//GEN-LAST:event_bUsunUsgActionPerformed

    private void cbUsgListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUsgListaItemStateChanged
        try {
            u = uZrodlo.pobierzBadanieUsgBD(((Badanie) cbUsgLista.getSelectedItem()).getId());
            tfUsgId.setText(String.valueOf(u.getId()));
            tfUsgPobyt.setText(String.valueOf(u.getPb().getId()));
            tfUsgLekarz.setText(String.valueOf(u.getLekarz().getId()));
            tfUsgDataBad.setText(u.getDataBadania().toString());
            tfUsgOpis.setText(u.getWynikOpisowy());
            cbUsgListaNazw.setSelectedItem(u);
        } catch (SQLException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbUsgListaItemStateChanged

    private void bZapiszEkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZapiszEkgActionPerformed
        eZrodlo = new EkgZrodlo();
        int weBId = tfEkgId.getText() == null || tfEkgId.getText().isEmpty() ? 0 : Integer.parseInt(tfEkgId.getText());
        int wePbId = Integer.parseInt(tfEkgPobyt.getText());
        int weBLk = Integer.parseInt(tfEkgLekarz.getText());
        Date weBDataBad = null;
        try {
            weBDataBad = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(tfEkgDataBad.getText());
        } catch (ParseException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
        String weBOpis = tfEkgOpis.getText();
        int weERytm = Integer.parseInt(tfEkgRytm.getText());
        int weEWar1 = Integer.parseInt(tfEkgWar1.getText());
        BigDecimal weEWar2 = new BigDecimal(tfEkgWar2.getText());

        try {
            if (weBId == 0) {
                weBId = eZrodlo.dodajBadanieEkg(wePbId, weBLk, weBDataBad, weBOpis, weERytm, weEWar1, weEWar2);
                tfEkgId.setText(String.valueOf(weBId));
                JOptionPane.showMessageDialog(this, "Dodano badanie " + weBId);
            } else {
                eZrodlo.aktualizujBadanieEkg(weBId, weBLk, weBDataBad, weBOpis, weERytm, weEWar1, weEWar2);
                JOptionPane.showMessageDialog(this, "Zaktualizowano badanie " + weBId);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
        lListaBadanEkg.setText("Lista badań: ");
        cbEkgLista.setVisible(true);
    }//GEN-LAST:event_bZapiszEkgActionPerformed

    private void bUsunEkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsunEkgActionPerformed
        usunBadanie(cbEkgLista);
    }//GEN-LAST:event_bUsunEkgActionPerformed

    private void cbEkgListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEkgListaItemStateChanged
        try {
            e = eZrodlo.pobierzBadanieEkgBD(((Badanie) cbEkgLista.getSelectedItem()).getId());
            tfEkgId.setText(String.valueOf(e.getId()));
            tfEkgPobyt.setText(String.valueOf(e.getPb().getId()));
            tfEkgLekarz.setText(String.valueOf(e.getLekarz().getId()));
            tfEkgDataBad.setText(e.getDataBadania().toString());
            tfEkgOpis.setText(e.getWynikOpisowy());
            tfEkgRytm.setText(String.valueOf(e.getRytm()));
            tfEkgWar1.setText(String.valueOf(e.getWar1()));
            tfEkgWar2.setText(String.valueOf(e.getWar2()));
        } catch (SQLException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbEkgListaItemStateChanged

    public void usunBadanie(JComboBox cbBadanieLista) {
        try {
            int usunBadanie = bZrodlo.usunBadanie(((Badanie) cbBadanieLista.getSelectedItem()).getId());
            JOptionPane.showMessageDialog(this, "Usunięto badanie " + usunBadanie);
        } catch (SQLException ex) {
            Logger.getLogger(OknoSzczegolowe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Formularze;
    private javax.swing.JButton bUsunEkg;
    private javax.swing.JButton bUsunUsg;
    private javax.swing.JButton bZapiszEkg;
    private javax.swing.JButton bZapiszUsg;
    private javax.swing.JComboBox<Badanie> cbEkgLista;
    private javax.swing.JComboBox<Badanie> cbUsgLista;
    private javax.swing.JComboBox<Usg> cbUsgListaNazw;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lListaBadanEkg;
    private javax.swing.JLabel lListaBadanUsg;
    private javax.swing.JPanel pDodajBadanie;
    private javax.swing.JPanel pEkg;
    private javax.swing.JPanel pUsg;
    private javax.swing.JTextArea taLekarz;
    private javax.swing.JTextArea taPacjent;
    private javax.swing.JTextArea taPobyt;
    private javax.swing.JTextField tfEkgDataBad;
    private javax.swing.JTextField tfEkgId;
    private javax.swing.JTextField tfEkgLekarz;
    private javax.swing.JTextArea tfEkgOpis;
    private javax.swing.JTextField tfEkgPobyt;
    private javax.swing.JTextField tfEkgRytm;
    private javax.swing.JTextField tfEkgWar1;
    private javax.swing.JTextField tfEkgWar2;
    private javax.swing.JTextField tfUsgDataBad;
    private javax.swing.JTextField tfUsgId;
    private javax.swing.JTextField tfUsgLekarz;
    private javax.swing.JTextArea tfUsgOpis;
    private javax.swing.JTextField tfUsgPobyt;
    private javax.swing.JTabbedPane tpBadania;
    // End of variables declaration//GEN-END:variables
}
